## 0. Load imports

In [2]:
## imports
import pandas as pd
import numpy as np


## print multiple things from same cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## 0. Load data

In [3]:
## load data on 2020 crimes in DC
df = dc_crim_2020 = pd.read_csv("https://opendata.arcgis.com/datasets/f516e0dd7b614b088ad781b0c4002331_2.csv")
dc_crim_2020.head()
dc_crim_2020.shape
dc_crim_2020.info()

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID
0,394625.0,137287.0,20124560,2020/09/01 01:04:31+00,2020/08/31 17:27:23+00,2020/08/31 17:35:25+00,3100 - 3199 BLOCK OF SOUTH STREET NW,THEFT F/AUTO,OTHERS,EVENING,...,000102 3,102.0,Precinct 5,GEORGETOWN,394625.0,137287.0,38.903422,-77.061967,916389269,NaN
1,397519.0,140084.0,20086996,2020/06/12 17:39:16+00,2020/06/11 13:00:10+00,2020/06/12 13:00:17+00,1100 - 1299 BLOCK OF IRVING STREET NW,MOTOR VEHICLE THEFT,OTHERS,DAY,...,003000 2,3000.0,Precinct 39,NaN,397519.0,140084.0,38.928631,-77.028613,916389270,NaN
2,396964.0,137650.0,20121383,2020/08/25 16:47:05+00,2020/08/25 01:00:19+00,2020/08/25 08:00:27+00,1500 - 1549 BLOCK OF MASSACHUSETTS AVENUE NW,THEFT/OTHER,OTHERS,DAY,...,010100 1,10100.0,Precinct 17,DOWNTOWN,396964.0,137650.0,38.906703,-77.035003,916389271,NaN
3,399763.0,130906.0,20027672,2020/02/15 01:13:21+00,2020/02/14 06:00:30+00,2020/02/14 23:00:35+00,301 - 499 BLOCK OF ORANGE STREET SE,MOTOR VEHICLE THEFT,OTHERS,EVENING,...,010400 2,10400.0,Precinct 123,NaN,399763.0,130906.0,38.845956,-77.002730,916389296,NaN
4,394895.0,140924.0,20029676,2020/02/18 18:25:49+00,2020/02/18 17:20:59+00,2020/02/18 18:25:59+00,3500 - 3599 BLOCK OF CONNECTICUT AVENUE NW,THEFT/OTHER,OTHERS,DAY,...,000600 2,600.0,Precinct 27,NaN,394895.0,140924.0,38.936187,-77.058881,916389297,NaN

(27931, 25)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27931 entries, 0 to 27930
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   X                     27931 non-null  float64
 1   Y                     27931 non-null  float64
 2   CCN                   27931 non-null  int64
 3   REPORT_DAT            27931 non-null  object
 4   START_DATE            27931 non-null  object
 5   END_DATE              24850 non-null  object
 6   BLOCK                 27931 non-null  object
 7   OFFENSE               27931 non-null  object
 8   METHOD                27931 non-null  object
 9   SHIFT                 27931 non-null  object
 10  WARD                  27931 non-null  int64
 11  ANC                   27931 non-null  object
 12  DISTRICT              27902 non-null  float64
 13  PSA                   27896 non-null  float64
 14  NEIGHBORHOOD_CLUSTER  27931 non-null  object
 15  BLOCK_GROUP           27930 non-null  object
 16  CENSUS_TRACT          27930 non-null  float64
 17  VOTING_PRECINCT       27931 non-null  object
 18  BID                   4658 non-null   object
 19  XBLOCK                27931 non-null  float64
 20  YBLOCK                27931 non-null  float64
 21  LATITUDE              27931 non-null  float64
 22  LONGITUDE             27931 non-null  float64
 23  OBJECTID              27931 non-null  int64
 24  OCTO_RECORD_ID        0 non-null      float64
dtypes: float64(10), int64(3), object(12)
memory usage: 5.3+ MB

In [4]:
a = [1,2,3]
b = ["a","b","c"]

In [5]:
fake_dict = dict( zip(a,b) )

fake_dict[1]

'a'

In [6]:
"QSS" in "QSS20"

True

In [7]:
list_classes = ["QSS20", "QSS17", "QSS45", "ECON1", "CS31", "CS74"]

In [8]:
empty_list = []
for c in list_classes:
    if "QSS" in c:
        empty_list.append(c)
        
empty_list

['QSS20', 'QSS17', 'QSS45']

In [9]:
[ c for c in list_classes if "QSS" in c  ]

['QSS20', 'QSS17', 'QSS45']

#### Warm-up: Ways to add 100 to column X

In [10]:
%%time
df.X + 100

CPU times: user 589 μs, sys: 144 μs, total: 733 μs
Wall time: 677 μs

0        394725.0
1        397619.0
2        397064.0
3        399863.0
4        394995.0
           ...
27926    403065.0
27927    397799.0
27928    394837.0
27929    399795.0
27930    401356.0
Name: X, Length: 27931, dtype: float64

## 1. Aggregation

### Example of grouping by one variable and doing one aggregation 

**Task**: find and print the number of unique offense types (`OFFENSE`) by ward (`WARD`)

In [11]:
df.groupby('WARD').agg({"OFFENSE": "nunique"}).reset_index()

   WARD  OFFENSE
0     1        9
1     2        9
2     3        8
3     4        8
4     5        9
5     6        9
6     7        9
7     8        9

In [12]:
for i, sub_df in df.groupby("WARD"):
    if i==3:
        break

In [13]:
sub_df.OFFENSE.nunique()

8

### Example of grouping by one variable and providing two summaries of the same variable

**Task**: previous showed number of offenses by ward but want to find out content of offenses in each ward; create an aggregation that summarizes both the number of unique offenses by ward and what those offenses are -- for instance, by pasting the unique offenses in that ward separated by the ";" (e.g., Theft; Burglary;...)

*Hint*: you can use the join command to paste together a list separated by some delimiter. 
    - The syntax, if we are using the comma delimiter, is: ", ".join(nameoflist)

In [23]:
## prof's example
for i, sub_df in df.groupby("WARD"):
    break

In [31]:
", ".join(sub_df.OFFENSE.unique()) #just sub_df.OFFENSE.unique provides array. this join function is a way of joining strings

'MOTOR VEHICLE THEFT, THEFT/OTHER, THEFT F/AUTO, BURGLARY, ROBBERY, ASSAULT W/DANGEROUS WEAPON, SEX ABUSE, HOMICIDE, ARSON'

In [33]:
df.groupby("WARD")["OFFENSE"].agg([
    "nunique",
    lambda x: ", ".join( x.unique() )])

      nunique                                         <lambda_0>
WARD
1           9  MOTOR VEHICLE THEFT, THEFT/OTHER, THEFT F/AUTO...
2           9  THEFT F/AUTO, THEFT/OTHER, ASSAULT W/DANGEROUS...
3           8  THEFT/OTHER, THEFT F/AUTO, ROBBERY, MOTOR VEHI...
4           8  MOTOR VEHICLE THEFT, THEFT F/AUTO, THEFT/OTHER...
5           9  THEFT/OTHER, ROBBERY, THEFT F/AUTO, MOTOR VEHI...
6           9  MOTOR VEHICLE THEFT, BURGLARY, THEFT/OTHER, TH...
7           9  MOTOR VEHICLE THEFT, THEFT F/AUTO, THEFT/OTHER...
8           9  MOTOR VEHICLE THEFT, ASSAULT W/DANGEROUS WEAPO...

### Example of grouping by two variables 

**Task**: group by ward (`WARD`) and police shift (`SHIFT`) and find the offense that is most common in that ward and shift

In [35]:
df.groupby(["WARD", "SHIFT"])["OFFENSE"].apply(lambda x : x.mode())

WARD  SHIFT
1     DAY       0                   THEFT/OTHER
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
2     DAY       0                   THEFT/OTHER
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
3     DAY       0                   THEFT/OTHER
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
4     DAY       0                  THEFT F/AUTO
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
5     DAY       0                  THEFT F/AUTO
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
6     DAY       0                   THEFT/OTHER
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
7     DAY       0                  THEFT F/AUTO
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
8     DAY       0                  THEFT F/AUTO
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0    ASSAULT W/DANGEROUS WEAPON
Name: OFFENSE, dtype: object

## Summarizing over all rows or all columns (without grouping)

We can also use the `apply` function to summarize rows or columns efficiently

**Task**: find the mean lat and longitude in one line of code

In [36]:
df[["LATITUDE", "LONGITUDE"]].apply(np.mean, axis = 0)

LATITUDE     38.907610
LONGITUDE   -77.007047
dtype: float64

## 2. Creating new columns/transforming their type

### Simple filtering

`np.where` is in the numpy package (aliased as `np`) and operates similar to `ifelse` in R

But there is a built in pandas way to emulate this.

**Task**: create an indicator `is_theft` for any offense that contains the word "THEFT"
    
**Task**: create an indicator `is_theft_notmotor` for any offense that contains the word "THEFT" but does not contain the word "MOTOR"

In [38]:
df["is_theft"] = df.OFFENSE.str.contains("THEFT")
df

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,CENSUS_TRACT,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID,is_theft
0,394625.0,137287.0,20124560,2020/09/01 01:04:31+00,2020/08/31 17:27:23+00,2020/08/31 17:35:25+00,3100 - 3199 BLOCK OF SOUTH STREET NW,THEFT F/AUTO,OTHERS,EVENING,...,102.0,Precinct 5,GEORGETOWN,394625.0,137287.0,38.903422,-77.061967,916389269,NaN,True
1,397519.0,140084.0,20086996,2020/06/12 17:39:16+00,2020/06/11 13:00:10+00,2020/06/12 13:00:17+00,1100 - 1299 BLOCK OF IRVING STREET NW,MOTOR VEHICLE THEFT,OTHERS,DAY,...,3000.0,Precinct 39,NaN,397519.0,140084.0,38.928631,-77.028613,916389270,NaN,True
2,396964.0,137650.0,20121383,2020/08/25 16:47:05+00,2020/08/25 01:00:19+00,2020/08/25 08:00:27+00,1500 - 1549 BLOCK OF MASSACHUSETTS AVENUE NW,THEFT/OTHER,OTHERS,DAY,...,10100.0,Precinct 17,DOWNTOWN,396964.0,137650.0,38.906703,-77.035003,916389271,NaN,True
3,399763.0,130906.0,20027672,2020/02/15 01:13:21+00,2020/02/14 06:00:30+00,2020/02/14 23:00:35+00,301 - 499 BLOCK OF ORANGE STREET SE,MOTOR VEHICLE THEFT,OTHERS,EVENING,...,10400.0,Precinct 123,NaN,399763.0,130906.0,38.845956,-77.002730,916389296,NaN,True
4,394895.0,140924.0,20029676,2020/02/18 18:25:49+00,2020/02/18 17:20:59+00,2020/02/18 18:25:59+00,3500 - 3599 BLOCK OF CONNECTICUT AVENUE NW,THEFT/OTHER,OTHERS,DAY,...,600.0,Precinct 27,NaN,394895.0,140924.0,38.936187,-77.058881,916389297,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27926,402965.0,132500.0,20138254,2020/09/28 03:26:22+00,2020/09/28 01:52:13+00,2020/09/28 02:33:37+00,2800 - 2999 BLOCK OF ALABAMA AVENUE SE,THEFT/OTHER,OTHERS,MIDNIGHT,...,7604.0,Precinct 113,NaN,402965.0,132500.0,38.860310,-76.965838,916979024,NaN,True
27927,397699.0,136946.0,20080236,2020/05/31 08:06:52+00,2020/05/31 05:39:20+00,2020/05/31 07:56:12+00,1000 - 1099 BLOCK OF PALMER ALLEY NW,BURGLARY,OTHERS,MIDNIGHT,...,5802.0,Precinct 129,DOWNTOWN,397699.0,136946.0,38.900364,-77.026527,916979098,NaN,False
27928,394737.0,137483.0,20080735,2020/06/01 05:23:06+00,2020/06/01 04:11:16+00,2020/06/01 04:30:20+00,3036 - 3099 BLOCK OF M STREET NW,BURGLARY,OTHERS,MIDNIGHT,...,102.0,Precinct 5,GEORGETOWN,394737.0,137483.0,38.905188,-77.060677,916979099,NaN,False
27929,399695.0,137774.0,20081545,2020/06/02 05:52:37+00,2020/06/02 02:45:36+00,2020/06/02 02:48:58+00,1300 - 1399 BLOCK OF 2ND STREET NE,BURGLARY,OTHERS,MIDNIGHT,...,10601.0,Precinct 144,NOMA,399695.0,137774.0,38.907825,-77.003516,916979100,NaN,False
27930,401256.0,135210.0,20162970,2020/11/14 16:24:24+00,2020/11/13 16:24:34+00,2020/11/14 16:24:36+00,300 - 399 BLOCK OF 14TH STREET SE,THEFT F/AUTO,OTHERS,DAY,...,6900.0,Precinct 87,NaN,401256.0,135210.0,38.884727,-76.985524,916979112,NaN,True

In [44]:
df["is_theft_notmotor"] = df.OFFENSE.str.contains("THEFT") & ~df.OFFENSE.str.contains( "MOTOR")
df

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID,is_theft,is_theft_notmotor
0,394625.0,137287.0,20124560,2020/09/01 01:04:31+00,2020/08/31 17:27:23+00,2020/08/31 17:35:25+00,3100 - 3199 BLOCK OF SOUTH STREET NW,THEFT F/AUTO,OTHERS,EVENING,...,Precinct 5,GEORGETOWN,394625.0,137287.0,38.903422,-77.061967,916389269,NaN,True,True
1,397519.0,140084.0,20086996,2020/06/12 17:39:16+00,2020/06/11 13:00:10+00,2020/06/12 13:00:17+00,1100 - 1299 BLOCK OF IRVING STREET NW,MOTOR VEHICLE THEFT,OTHERS,DAY,...,Precinct 39,NaN,397519.0,140084.0,38.928631,-77.028613,916389270,NaN,True,False
2,396964.0,137650.0,20121383,2020/08/25 16:47:05+00,2020/08/25 01:00:19+00,2020/08/25 08:00:27+00,1500 - 1549 BLOCK OF MASSACHUSETTS AVENUE NW,THEFT/OTHER,OTHERS,DAY,...,Precinct 17,DOWNTOWN,396964.0,137650.0,38.906703,-77.035003,916389271,NaN,True,True
3,399763.0,130906.0,20027672,2020/02/15 01:13:21+00,2020/02/14 06:00:30+00,2020/02/14 23:00:35+00,301 - 499 BLOCK OF ORANGE STREET SE,MOTOR VEHICLE THEFT,OTHERS,EVENING,...,Precinct 123,NaN,399763.0,130906.0,38.845956,-77.002730,916389296,NaN,True,False
4,394895.0,140924.0,20029676,2020/02/18 18:25:49+00,2020/02/18 17:20:59+00,2020/02/18 18:25:59+00,3500 - 3599 BLOCK OF CONNECTICUT AVENUE NW,THEFT/OTHER,OTHERS,DAY,...,Precinct 27,NaN,394895.0,140924.0,38.936187,-77.058881,916389297,NaN,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27926,402965.0,132500.0,20138254,2020/09/28 03:26:22+00,2020/09/28 01:52:13+00,2020/09/28 02:33:37+00,2800 - 2999 BLOCK OF ALABAMA AVENUE SE,THEFT/OTHER,OTHERS,MIDNIGHT,...,Precinct 113,NaN,402965.0,132500.0,38.860310,-76.965838,916979024,NaN,True,True
27927,397699.0,136946.0,20080236,2020/05/31 08:06:52+00,2020/05/31 05:39:20+00,2020/05/31 07:56:12+00,1000 - 1099 BLOCK OF PALMER ALLEY NW,BURGLARY,OTHERS,MIDNIGHT,...,Precinct 129,DOWNTOWN,397699.0,136946.0,38.900364,-77.026527,916979098,NaN,False,False
27928,394737.0,137483.0,20080735,2020/06/01 05:23:06+00,2020/06/01 04:11:16+00,2020/06/01 04:30:20+00,3036 - 3099 BLOCK OF M STREET NW,BURGLARY,OTHERS,MIDNIGHT,...,Precinct 5,GEORGETOWN,394737.0,137483.0,38.905188,-77.060677,916979099,NaN,False,False
27929,399695.0,137774.0,20081545,2020/06/02 05:52:37+00,2020/06/02 02:45:36+00,2020/06/02 02:48:58+00,1300 - 1399 BLOCK OF 2ND STREET NE,BURGLARY,OTHERS,MIDNIGHT,...,Precinct 144,NOMA,399695.0,137774.0,38.907825,-77.003516,916979100,NaN,False,False
27930,401256.0,135210.0,20162970,2020/11/14 16:24:24+00,2020/11/13 16:24:34+00,2020/11/14 16:24:36+00,300 - 399 BLOCK OF 14TH STREET SE,THEFT F/AUTO,OTHERS,DAY,...,Precinct 87,NaN,401256.0,135210.0,38.884727,-76.985524,916979112,NaN,True,True

### np.select

**Task**: create a new variable, `offense_summary`, where you:
        
- Recode theft offenses that use a gun or knife as the method (`METHOD`) as: violent theft
- Recode non-theft offenses that use a gun or knife as the method as: violent other
- Recode all other as non-violent

In [46]:
df["offense_summary"] = np.select(

KeyError: 'offense_summary'

### map.recode

**Task**: recode shifts that are MIDNIGHT or EVENING as "nighttime"; code other shift to daytime

### Using built-in pandas methods

Another way of creating variables, used either alone or in combination with np.where and np.select is to use pandas built in `str` methods

Basic structure is: `df['namestringcol'].str.someoperation`

**Task**: using a `str` method, create a new column--`OFFENSE_NOSP`--that replaces spaces in the `OFFENSE` column with underscores

### Transforming column types

**Task**: check the type of the `START_DATE` column

**Task**: recast the `START_DATE` column to datetime, calling this `START_DATE_CLEAN`; coerce errors rather than cleaning the string; check the type of that new col

**Task:** print the min and max of `START_DATE_CLEAN`. What happens if you try to do this with `START_DATE`?

## 3. Row and column filtering

### Row subsetting

**Task**: filter to crime reports about theft using the `is_theft` definition and that are in ward 3

### Column subsetting

**Task**: select two columns--`START_DATE` and `END_DATE`--and print the head of the dataframe

**Task**: use list comprehension to automate this a bit and select all columns with the word "DATE" in the name; print the head of the dataframe

**Task**: filter reports of crime in `START_DATE_CLEAN` before May 2020 and that are located in ward 1; select the ward and `START_DATE` column and print a random sample of rows