## 0. Load imports

In [7]:
## imports
import pandas as pd
import numpy as np


## print multiple things from same cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## 0. Load data

In [11]:
## load data on 2020 crimes in DC
df = dc_crim_2020 = pd.read_csv("https://opendata.arcgis.com/datasets/f516e0dd7b614b088ad781b0c4002331_2.csv")
dc_crim_2020.head()
dc_crim_2020.shape
dc_crim_2020.info()

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID
0,400541.0,139301.0,20113555,2020/08/09 11:29:56+00,2020/08/08 23:00:41+00,2020/08/09 11:00:15+00,2300 - 2499 BLOCK OF WASHINGTON PLACE NE,THEFT F/AUTO,OTHERS,DAY,...,009102 4,9102.0,Precinct 72,NaN,400541.0,139301.0,38.921581,-76.993761,926034654,NaN
1,398413.0,137185.0,20121119,2020/08/25 02:14:34+00,2020/08/25 00:58:55+00,2020/08/25 01:55:13+00,444 - 499 BLOCK OF K STREET NW,MOTOR VEHICLE THEFT,OTHERS,EVENING,...,004702 4,4702.0,Precinct 1,MOUNT VERNON TRIANGLE CID,398413.0,137185.0,38.902518,-77.018296,926034655,NaN
2,402411.0,131808.0,20103698,2020/07/19 20:53:10+00,2020/07/13 12:27:40+00,2020/07/13 12:37:52+00,2300 - 2499 BLOCK OF HARTFORD STREET SE,THEFT F/AUTO,OTHERS,EVENING,...,007408 2,7408.0,Precinct 115,NaN,402411.0,131808.0,38.854078,-76.972223,926034656,NaN
3,397115.0,137836.0,20109702,2020/08/01 18:43:34+00,2020/07/28 14:00:04+00,2020/07/28 15:30:10+00,1400 - 1499 BLOCK OF RHODE ISLAND AVENUE NW,THEFT/OTHER,OTHERS,DAY,...,005203 1,5203.0,Precinct 17,NaN,397115.0,137836.0,38.908379,-77.033263,926034666,NaN
4,397745.0,138854.0,20022073,2020/02/06 01:41:31+00,2020/02/05 23:30:54+00,2020/02/06 00:30:05+00,2000 - 2099 BLOCK OF 10TH STREET NW,THEFT F/AUTO,OTHERS,EVENING,...,004401 3,4401.0,Precinct 22,NaN,397745.0,138854.0,38.917552,-77.026002,926034688,NaN

(27932, 25)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27932 entries, 0 to 27931
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   X                     27932 non-null  float64
 1   Y                     27932 non-null  float64
 2   CCN                   27932 non-null  int64
 3   REPORT_DAT            27932 non-null  object
 4   START_DATE            27932 non-null  object
 5   END_DATE              24851 non-null  object
 6   BLOCK                 27932 non-null  object
 7   OFFENSE               27932 non-null  object
 8   METHOD                27932 non-null  object
 9   SHIFT                 27932 non-null  object
 10  WARD                  27932 non-null  int64
 11  ANC                   27932 non-null  object
 12  DISTRICT              27903 non-null  float64
 13  PSA                   27897 non-null  float64
 14  NEIGHBORHOOD_CLUSTER  27932 non-null  object
 15  BLOCK_GROUP           27931 non-null  object
 16  CENSUS_TRACT          27931 non-null  float64
 17  VOTING_PRECINCT       27932 non-null  object
 18  BID                   4658 non-null   object
 19  XBLOCK                27932 non-null  float64
 20  YBLOCK                27932 non-null  float64
 21  LATITUDE              27932 non-null  float64
 22  LONGITUDE             27932 non-null  float64
 23  OBJECTID              27932 non-null  int64
 24  OCTO_RECORD_ID        0 non-null      float64
dtypes: float64(10), int64(3), object(12)
memory usage: 5.3+ MB

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [16]:
a = [1,2,3]
b = ["a","b","c"]

In [19]:
fake_dict = dict( zip(a,b) )

fake_dict

fake_dict[1]

{1: 'a', 2: 'b', 3: 'c'}

'a'

In [64]:
"QSS" in "QSS20"

True

In [22]:
list_classes = ["QSS20", "QSS17", "QSS45", "ECON1", "CS31", "CS74"]

In [23]:
empty_list = []
for c in list_classes:
    if "QSS" in c:
        empty_list.append(c)
        
empty_list

['QSS20', 'QSS17', 'QSS45']

In [26]:
[ c for c in list_classes if "QSS" in c  ]

['QSS20', 'QSS17', 'QSS45']

#### Warm-up: Ways to add 100 to column X

In [68]:
%%time
df.X + 100

CPU times: user 797 μs, sys: 317 μs, total: 1.11 ms
Wall time: 1.03 ms

0        402474.0
1        398020.0
2        402511.0
3        398489.0
4        399046.0
           ...
27927    397341.0
27928    397428.0
27929    405149.0
27930    399923.0
27931    400901.0
Name: X, Length: 27932, dtype: float64

## 1. Aggregation

### Example of grouping by one variable and doing one aggregation 

**Task**: find and print the number of unique offense types (`OFFENSE`) by ward (`WARD`)

In [28]:
df.groupby("WARD")["OFFENSE"].nunique().reset_index()

   WARD  OFFENSE
0     1        9
1     2        9
2     3        8
3     4        8
4     5        9
5     6        9
6     7        9
7     8        9

In [4]:
df.groupby('WARD').agg({"OFFENSE": "nunique"}).reset_index()

   WARD  OFFENSE
0     1        9
1     2        9
2     3        8
3     4        8
4     5        9
5     6        9
6     7        9
7     8        9

In [70]:
for i, sub_df in df.groupby("WARD"):
    if i==3:
        break

In [71]:
sub_df.OFFENSE.nunique()

8

### Example of grouping by one variable and providing two summaries of the same variable

**Task**: previous showed number of offenses by ward but want to find out content of offenses in each ward; create an aggregation that summarizes both the number of unique offenses by ward and what those offenses are -- for instance, by pasting the unique offenses in that ward separated by the ";" (e.g., Theft; Burglary;...)

*Hint*: you can use the join command to paste together a list separated by some delimiter. 
    - The syntax, if we are using the comma delimiter, is: ", ".join(nameoflist)

In [72]:
## prof's example
for i, sub_df in df.groupby("WARD"):
    break

In [73]:
", ".join(sub_df.OFFENSE.unique()) #just sub_df.OFFENSE.unique provides array. this join function is a way of joining strings

'THEFT/OTHER, THEFT F/AUTO, MOTOR VEHICLE THEFT, BURGLARY, ROBBERY, SEX ABUSE, ASSAULT W/DANGEROUS WEAPON, HOMICIDE, ARSON'

In [10]:
df.groupby("WARD")["OFFENSE"].agg([
    "nunique",
    lambda x: ", ".join( x.unique() )])

      nunique                                         <lambda_0>
WARD
1           9  THEFT/OTHER, THEFT F/AUTO, MOTOR VEHICLE THEFT...
2           9  THEFT F/AUTO, THEFT/OTHER, ROBBERY, MOTOR VEHI...
3           8  ROBBERY, THEFT F/AUTO, THEFT/OTHER, MOTOR VEHI...
4           8  THEFT F/AUTO, THEFT/OTHER, ROBBERY, MOTOR VEHI...
5           9  BURGLARY, THEFT/OTHER, THEFT F/AUTO, MOTOR VEH...
6           9  THEFT/OTHER, HOMICIDE, THEFT F/AUTO, BURGLARY,...
7           9  MOTOR VEHICLE THEFT, ASSAULT W/DANGEROUS WEAPO...
8           9  HOMICIDE, ASSAULT W/DANGEROUS WEAPON, MOTOR VE...

### Example of grouping by two variables 

**Task**: group by ward (`WARD`) and police shift (`SHIFT`) and find the offense that is most common in that ward and shift

In [13]:
df.groupby(["WARD", "SHIFT"])["OFFENSE"].apply(lambda x: x.mode())

WARD  SHIFT
1     DAY       0                   THEFT/OTHER
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
2     DAY       0                   THEFT/OTHER
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
3     DAY       0                   THEFT/OTHER
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
4     DAY       0                  THEFT F/AUTO
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
5     DAY       0                  THEFT F/AUTO
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
6     DAY       0                   THEFT/OTHER
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
7     DAY       0                  THEFT F/AUTO
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
8     DAY       0                  THEFT F/AUTO
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0    ASSAULT W/DANGEROUS WEAPON
Name: OFFENSE, dtype: object

In [75]:
df.groupby(["WARD", "SHIFT"])["OFFENSE"].apply(lambda x : x.mode())

WARD  SHIFT
1     DAY       0                   THEFT/OTHER
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
2     DAY       0                   THEFT/OTHER
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
3     DAY       0                   THEFT/OTHER
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
4     DAY       0                  THEFT F/AUTO
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
5     DAY       0                  THEFT F/AUTO
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
6     DAY       0                   THEFT/OTHER
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
7     DAY       0                  THEFT F/AUTO
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0                   THEFT/OTHER
8     DAY       0                  THEFT F/AUTO
      EVENING   0                   THEFT/OTHER
      MIDNIGHT  0    ASSAULT W/DANGEROUS WEAPON
Name: OFFENSE, dtype: object

## Summarizing over all rows or all columns (without grouping)

We can also use the `apply` function to summarize rows or columns efficiently

**Task**: find the mean lat and longitude in one line of code

In [13]:
df[["LATITUDE", "LONGITUDE"]].apply(np.mean, axis = 0)

LATITUDE     38.907611
LONGITUDE   -77.007045
dtype: float64

## 2. Creating new columns/transforming their type

### Simple filtering

`np.where` is in the numpy package (aliased as `np`) and operates similar to `ifelse` in R

But there is a built in pandas way to emulate this.

**Task**: create an indicator `is_theft` for any offense that contains the word "THEFT"
    
**Task**: create an indicator `is_theft_notmotor` for any offense that contains the word "THEFT" but does not contain the word "MOTOR"

In [77]:
df["is_theft"] = df.OFFENSE.str.contains("THEFT")
df

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,CENSUS_TRACT,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID,is_theft
0,402374.0,132186.0,10251445,2020/09/11 04:00:00+00,2010/09/02 04:00:00+00,2010/09/02 04:00:00+00,2300 - 2399 BLOCK OF AINGER PLACE SE,HOMICIDE,GUN,MIDNIGHT,...,7502.0,Precinct 134,NaN,402374.0,132186.0,38.857483,-76.972648,921212443,NaN,False
1,397920.0,136943.0,5370,2020/01/17 02:39:05+00,2020/01/11 02:48:51+00,2020/01/17 02:48:54+00,800 - 899 BLOCK OF 9TH STREET NW,THEFT F/AUTO,OTHERS,EVENING,...,5802.0,Precinct 129,DOWNTOWN,397920.0,136943.0,38.900337,-77.023979,921212447,NaN,True
2,402411.0,131808.0,10147537,2020/12/21 05:00:00+00,2010/10/10 02:00:00+00,NaN,2300 - 2499 BLOCK OF HARTFORD STREET SE,HOMICIDE,OTHERS,MIDNIGHT,...,7408.0,Precinct 115,NaN,402411.0,131808.0,38.854078,-76.972223,921212449,NaN,False
3,398389.0,140433.0,20000957,2020/01/02 18:53:05+00,2019/12/30 20:00:20+00,2020/01/02 18:53:32+00,3300 - 3399 BLOCK OF PARK PLACE NW,THEFT/OTHER,OTHERS,DAY,...,3200.0,Precinct 38,NaN,398389.0,140433.0,38.931777,-77.018580,921213797,NaN,True
4,398946.0,139092.0,20001080,2020/01/03 01:55:16+00,2020/01/02 20:39:16+00,2020/01/02 22:20:27+00,2200 - 2299 BLOCK OF 1ST STREET NW,BURGLARY,OTHERS,EVENING,...,3301.0,Precinct 135,NaN,398946.0,139092.0,38.919698,-77.012154,921213798,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27927,397241.0,140302.0,20097822,2020/07/06 22:02:48+00,2020/07/06 20:42:59+00,2020/07/06 21:00:41+00,1325 - 1399 BLOCK OF PARK ROAD NW,ASSAULT W/DANGEROUS WEAPON,KNIFE,EVENING,...,2900.0,Precinct 41,NaN,397241.0,140302.0,38.930594,-77.031820,921779024,NaN,False
27928,397328.0,139157.0,20100870,2020/07/13 22:12:52+00,2020/07/07 18:00:45+00,2020/07/07 20:00:57+00,1300 - 1399 BLOCK OF FLORIDA AVENUE NW,THEFT F/AUTO,OTHERS,EVENING,...,4401.0,Precinct 22,NaN,397328.0,139157.0,38.920280,-77.030812,921779025,NaN,True
27929,405049.0,136086.0,20101193,2020/07/14 14:32:30+00,2020/07/11 22:00:31+00,2020/07/14 14:28:59+00,4200 - 4243 BLOCK OF BENNING ROAD NE,THEFT/OTHER,OTHERS,DAY,...,7803.0,Precinct 99,NaN,405049.0,136086.0,38.892605,-76.941800,921779026,NaN,True
27930,399823.0,138853.0,20400676,2020/05/01 18:58:30+00,2020/05/01 15:00:00+00,2020/05/01 15:35:00+00,1948 - 2099 BLOCK OF 3RD STREET NE,THEFT F/AUTO,OTHERS,DAY,...,8702.0,Precinct 75,NaN,399823.0,138853.0,38.917546,-77.002041,921779089,NaN,True
27931,400801.0,129945.0,20141517,2020/10/04 03:24:25+00,2020/10/04 01:03:42+00,2020/10/04 02:58:27+00,900 - 1299 BLOCK OF VALLEY AVENUE SE,MOTOR VEHICLE THEFT,OTHERS,MIDNIGHT,...,9700.0,Precinct 121,NaN,400801.0,129945.0,38.837298,-76.990774,921779151,NaN,True

In [78]:
df["is_theft_notmotor"] = df.OFFENSE.str.contains("THEFT") & ~df.OFFENSE.str.contains( "MOTOR")
df

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID,is_theft,is_theft_notmotor
0,402374.0,132186.0,10251445,2020/09/11 04:00:00+00,2010/09/02 04:00:00+00,2010/09/02 04:00:00+00,2300 - 2399 BLOCK OF AINGER PLACE SE,HOMICIDE,GUN,MIDNIGHT,...,Precinct 134,NaN,402374.0,132186.0,38.857483,-76.972648,921212443,NaN,False,False
1,397920.0,136943.0,5370,2020/01/17 02:39:05+00,2020/01/11 02:48:51+00,2020/01/17 02:48:54+00,800 - 899 BLOCK OF 9TH STREET NW,THEFT F/AUTO,OTHERS,EVENING,...,Precinct 129,DOWNTOWN,397920.0,136943.0,38.900337,-77.023979,921212447,NaN,True,True
2,402411.0,131808.0,10147537,2020/12/21 05:00:00+00,2010/10/10 02:00:00+00,NaN,2300 - 2499 BLOCK OF HARTFORD STREET SE,HOMICIDE,OTHERS,MIDNIGHT,...,Precinct 115,NaN,402411.0,131808.0,38.854078,-76.972223,921212449,NaN,False,False
3,398389.0,140433.0,20000957,2020/01/02 18:53:05+00,2019/12/30 20:00:20+00,2020/01/02 18:53:32+00,3300 - 3399 BLOCK OF PARK PLACE NW,THEFT/OTHER,OTHERS,DAY,...,Precinct 38,NaN,398389.0,140433.0,38.931777,-77.018580,921213797,NaN,True,True
4,398946.0,139092.0,20001080,2020/01/03 01:55:16+00,2020/01/02 20:39:16+00,2020/01/02 22:20:27+00,2200 - 2299 BLOCK OF 1ST STREET NW,BURGLARY,OTHERS,EVENING,...,Precinct 135,NaN,398946.0,139092.0,38.919698,-77.012154,921213798,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27927,397241.0,140302.0,20097822,2020/07/06 22:02:48+00,2020/07/06 20:42:59+00,2020/07/06 21:00:41+00,1325 - 1399 BLOCK OF PARK ROAD NW,ASSAULT W/DANGEROUS WEAPON,KNIFE,EVENING,...,Precinct 41,NaN,397241.0,140302.0,38.930594,-77.031820,921779024,NaN,False,False
27928,397328.0,139157.0,20100870,2020/07/13 22:12:52+00,2020/07/07 18:00:45+00,2020/07/07 20:00:57+00,1300 - 1399 BLOCK OF FLORIDA AVENUE NW,THEFT F/AUTO,OTHERS,EVENING,...,Precinct 22,NaN,397328.0,139157.0,38.920280,-77.030812,921779025,NaN,True,True
27929,405049.0,136086.0,20101193,2020/07/14 14:32:30+00,2020/07/11 22:00:31+00,2020/07/14 14:28:59+00,4200 - 4243 BLOCK OF BENNING ROAD NE,THEFT/OTHER,OTHERS,DAY,...,Precinct 99,NaN,405049.0,136086.0,38.892605,-76.941800,921779026,NaN,True,True
27930,399823.0,138853.0,20400676,2020/05/01 18:58:30+00,2020/05/01 15:00:00+00,2020/05/01 15:35:00+00,1948 - 2099 BLOCK OF 3RD STREET NE,THEFT F/AUTO,OTHERS,DAY,...,Precinct 75,NaN,399823.0,138853.0,38.917546,-77.002041,921779089,NaN,True,True
27931,400801.0,129945.0,20141517,2020/10/04 03:24:25+00,2020/10/04 01:03:42+00,2020/10/04 02:58:27+00,900 - 1299 BLOCK OF VALLEY AVENUE SE,MOTOR VEHICLE THEFT,OTHERS,MIDNIGHT,...,Precinct 121,NaN,400801.0,129945.0,38.837298,-76.990774,921779151,NaN,True,False

### np.select

**Task**: create a new variable, `offense_summary`, where you:
        
- Recode theft offenses that use a gun or knife as the method (`METHOD`) as: violent theft
- Recode non-theft offenses that use a gun or knife as the method as: violent other
- Recode all other as non-violent

In [29]:
df["METHOD"]

conditions = [
    df.METHOD.str.contains("GUN") | df.METHOD.str.contains("KNIFE") & df.OFFENSE.str.contains("THEFT"),
    df.METHOD.str.contains("GUN") | df.METHOD.str.contains("KNIFE") & ~df.OFFENSE.str.contains("THEFT")]

cat = ["violent theft", "violent other"]

df["offense_summary"] = np.select(conditions, cat, default="non-violent")

df

0           GUN
1        OTHERS
2        OTHERS
3        OTHERS
4        OTHERS
          ...
27927     KNIFE
27928    OTHERS
27929    OTHERS
27930    OTHERS
27931    OTHERS
Name: METHOD, Length: 27932, dtype: object

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,CENSUS_TRACT,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID,offense_summary
0,402374.0,132186.0,10251445,2020/09/11 04:00:00+00,2010/09/02 04:00:00+00,2010/09/02 04:00:00+00,2300 - 2399 BLOCK OF AINGER PLACE SE,HOMICIDE,GUN,MIDNIGHT,...,7502.0,Precinct 134,NaN,402374.0,132186.0,38.857483,-76.972648,921212443,NaN,violent theft
1,397920.0,136943.0,5370,2020/01/17 02:39:05+00,2020/01/11 02:48:51+00,2020/01/17 02:48:54+00,800 - 899 BLOCK OF 9TH STREET NW,THEFT F/AUTO,OTHERS,EVENING,...,5802.0,Precinct 129,DOWNTOWN,397920.0,136943.0,38.900337,-77.023979,921212447,NaN,non-violent
2,402411.0,131808.0,10147537,2020/12/21 05:00:00+00,2010/10/10 02:00:00+00,NaN,2300 - 2499 BLOCK OF HARTFORD STREET SE,HOMICIDE,OTHERS,MIDNIGHT,...,7408.0,Precinct 115,NaN,402411.0,131808.0,38.854078,-76.972223,921212449,NaN,non-violent
3,398389.0,140433.0,20000957,2020/01/02 18:53:05+00,2019/12/30 20:00:20+00,2020/01/02 18:53:32+00,3300 - 3399 BLOCK OF PARK PLACE NW,THEFT/OTHER,OTHERS,DAY,...,3200.0,Precinct 38,NaN,398389.0,140433.0,38.931777,-77.018580,921213797,NaN,non-violent
4,398946.0,139092.0,20001080,2020/01/03 01:55:16+00,2020/01/02 20:39:16+00,2020/01/02 22:20:27+00,2200 - 2299 BLOCK OF 1ST STREET NW,BURGLARY,OTHERS,EVENING,...,3301.0,Precinct 135,NaN,398946.0,139092.0,38.919698,-77.012154,921213798,NaN,non-violent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27927,397241.0,140302.0,20097822,2020/07/06 22:02:48+00,2020/07/06 20:42:59+00,2020/07/06 21:00:41+00,1325 - 1399 BLOCK OF PARK ROAD NW,ASSAULT W/DANGEROUS WEAPON,KNIFE,EVENING,...,2900.0,Precinct 41,NaN,397241.0,140302.0,38.930594,-77.031820,921779024,NaN,violent other
27928,397328.0,139157.0,20100870,2020/07/13 22:12:52+00,2020/07/07 18:00:45+00,2020/07/07 20:00:57+00,1300 - 1399 BLOCK OF FLORIDA AVENUE NW,THEFT F/AUTO,OTHERS,EVENING,...,4401.0,Precinct 22,NaN,397328.0,139157.0,38.920280,-77.030812,921779025,NaN,non-violent
27929,405049.0,136086.0,20101193,2020/07/14 14:32:30+00,2020/07/11 22:00:31+00,2020/07/14 14:28:59+00,4200 - 4243 BLOCK OF BENNING ROAD NE,THEFT/OTHER,OTHERS,DAY,...,7803.0,Precinct 99,NaN,405049.0,136086.0,38.892605,-76.941800,921779026,NaN,non-violent
27930,399823.0,138853.0,20400676,2020/05/01 18:58:30+00,2020/05/01 15:00:00+00,2020/05/01 15:35:00+00,1948 - 2099 BLOCK OF 3RD STREET NE,THEFT F/AUTO,OTHERS,DAY,...,8702.0,Precinct 75,NaN,399823.0,138853.0,38.917546,-77.002041,921779089,NaN,non-violent
27931,400801.0,129945.0,20141517,2020/10/04 03:24:25+00,2020/10/04 01:03:42+00,2020/10/04 02:58:27+00,900 - 1299 BLOCK OF VALLEY AVENUE SE,MOTOR VEHICLE THEFT,OTHERS,MIDNIGHT,...,9700.0,Precinct 121,NaN,400801.0,129945.0,38.837298,-76.990774,921779151,NaN,non-violent

### map.recode

**Task**: recode shifts that are MIDNIGHT or EVENING as "nighttime"; code other shift to daytime

In [80]:
shift = ["MIDNIGHT", "EVENING", "DAY"]

time = ["nighttime", "nighttime", "daytime"]

conversion_dict = dict(zip(shift, time))

df["SHIFT"] = df.SHIFT.map(conversion_dict)

df

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID,is_theft,is_theft_notmotor,offense_summary
0,402374.0,132186.0,10251445,2020/09/11 04:00:00+00,2010/09/02 04:00:00+00,2010/09/02 04:00:00+00,2300 - 2399 BLOCK OF AINGER PLACE SE,HOMICIDE,GUN,nighttime,...,NaN,402374.0,132186.0,38.857483,-76.972648,921212443,NaN,False,False,violent theft
1,397920.0,136943.0,5370,2020/01/17 02:39:05+00,2020/01/11 02:48:51+00,2020/01/17 02:48:54+00,800 - 899 BLOCK OF 9TH STREET NW,THEFT F/AUTO,OTHERS,nighttime,...,DOWNTOWN,397920.0,136943.0,38.900337,-77.023979,921212447,NaN,True,True,non-violent
2,402411.0,131808.0,10147537,2020/12/21 05:00:00+00,2010/10/10 02:00:00+00,NaN,2300 - 2499 BLOCK OF HARTFORD STREET SE,HOMICIDE,OTHERS,nighttime,...,NaN,402411.0,131808.0,38.854078,-76.972223,921212449,NaN,False,False,non-violent
3,398389.0,140433.0,20000957,2020/01/02 18:53:05+00,2019/12/30 20:00:20+00,2020/01/02 18:53:32+00,3300 - 3399 BLOCK OF PARK PLACE NW,THEFT/OTHER,OTHERS,daytime,...,NaN,398389.0,140433.0,38.931777,-77.018580,921213797,NaN,True,True,non-violent
4,398946.0,139092.0,20001080,2020/01/03 01:55:16+00,2020/01/02 20:39:16+00,2020/01/02 22:20:27+00,2200 - 2299 BLOCK OF 1ST STREET NW,BURGLARY,OTHERS,nighttime,...,NaN,398946.0,139092.0,38.919698,-77.012154,921213798,NaN,False,False,non-violent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27927,397241.0,140302.0,20097822,2020/07/06 22:02:48+00,2020/07/06 20:42:59+00,2020/07/06 21:00:41+00,1325 - 1399 BLOCK OF PARK ROAD NW,ASSAULT W/DANGEROUS WEAPON,KNIFE,nighttime,...,NaN,397241.0,140302.0,38.930594,-77.031820,921779024,NaN,False,False,violent other
27928,397328.0,139157.0,20100870,2020/07/13 22:12:52+00,2020/07/07 18:00:45+00,2020/07/07 20:00:57+00,1300 - 1399 BLOCK OF FLORIDA AVENUE NW,THEFT F/AUTO,OTHERS,nighttime,...,NaN,397328.0,139157.0,38.920280,-77.030812,921779025,NaN,True,True,non-violent
27929,405049.0,136086.0,20101193,2020/07/14 14:32:30+00,2020/07/11 22:00:31+00,2020/07/14 14:28:59+00,4200 - 4243 BLOCK OF BENNING ROAD NE,THEFT/OTHER,OTHERS,daytime,...,NaN,405049.0,136086.0,38.892605,-76.941800,921779026,NaN,True,True,non-violent
27930,399823.0,138853.0,20400676,2020/05/01 18:58:30+00,2020/05/01 15:00:00+00,2020/05/01 15:35:00+00,1948 - 2099 BLOCK OF 3RD STREET NE,THEFT F/AUTO,OTHERS,daytime,...,NaN,399823.0,138853.0,38.917546,-77.002041,921779089,NaN,True,True,non-violent
27931,400801.0,129945.0,20141517,2020/10/04 03:24:25+00,2020/10/04 01:03:42+00,2020/10/04 02:58:27+00,900 - 1299 BLOCK OF VALLEY AVENUE SE,MOTOR VEHICLE THEFT,OTHERS,nighttime,...,NaN,400801.0,129945.0,38.837298,-76.990774,921779151,NaN,True,False,non-violent

### Using built-in pandas methods

Another way of creating variables, used either alone or in combination with np.where and np.select is to use pandas built in `str` methods

Basic structure is: `df['namestringcol'].str.someoperation`

**Task**: using a `str` method, create a new column--`OFFENSE_NOSP`--that replaces spaces in the `OFFENSE` column with underscores

In [81]:
df["OFFENSE_NOSP"] = df["OFFENSE"].str.replace(" ", "_")

df

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID,is_theft,is_theft_notmotor,offense_summary,OFFENSE_NOSP
0,402374.0,132186.0,10251445,2020/09/11 04:00:00+00,2010/09/02 04:00:00+00,2010/09/02 04:00:00+00,2300 - 2399 BLOCK OF AINGER PLACE SE,HOMICIDE,GUN,nighttime,...,402374.0,132186.0,38.857483,-76.972648,921212443,NaN,False,False,violent theft,HOMICIDE
1,397920.0,136943.0,5370,2020/01/17 02:39:05+00,2020/01/11 02:48:51+00,2020/01/17 02:48:54+00,800 - 899 BLOCK OF 9TH STREET NW,THEFT F/AUTO,OTHERS,nighttime,...,397920.0,136943.0,38.900337,-77.023979,921212447,NaN,True,True,non-violent,THEFT_F/AUTO
2,402411.0,131808.0,10147537,2020/12/21 05:00:00+00,2010/10/10 02:00:00+00,NaN,2300 - 2499 BLOCK OF HARTFORD STREET SE,HOMICIDE,OTHERS,nighttime,...,402411.0,131808.0,38.854078,-76.972223,921212449,NaN,False,False,non-violent,HOMICIDE
3,398389.0,140433.0,20000957,2020/01/02 18:53:05+00,2019/12/30 20:00:20+00,2020/01/02 18:53:32+00,3300 - 3399 BLOCK OF PARK PLACE NW,THEFT/OTHER,OTHERS,daytime,...,398389.0,140433.0,38.931777,-77.018580,921213797,NaN,True,True,non-violent,THEFT/OTHER
4,398946.0,139092.0,20001080,2020/01/03 01:55:16+00,2020/01/02 20:39:16+00,2020/01/02 22:20:27+00,2200 - 2299 BLOCK OF 1ST STREET NW,BURGLARY,OTHERS,nighttime,...,398946.0,139092.0,38.919698,-77.012154,921213798,NaN,False,False,non-violent,BURGLARY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27927,397241.0,140302.0,20097822,2020/07/06 22:02:48+00,2020/07/06 20:42:59+00,2020/07/06 21:00:41+00,1325 - 1399 BLOCK OF PARK ROAD NW,ASSAULT W/DANGEROUS WEAPON,KNIFE,nighttime,...,397241.0,140302.0,38.930594,-77.031820,921779024,NaN,False,False,violent other,ASSAULT_W/DANGEROUS_WEAPON
27928,397328.0,139157.0,20100870,2020/07/13 22:12:52+00,2020/07/07 18:00:45+00,2020/07/07 20:00:57+00,1300 - 1399 BLOCK OF FLORIDA AVENUE NW,THEFT F/AUTO,OTHERS,nighttime,...,397328.0,139157.0,38.920280,-77.030812,921779025,NaN,True,True,non-violent,THEFT_F/AUTO
27929,405049.0,136086.0,20101193,2020/07/14 14:32:30+00,2020/07/11 22:00:31+00,2020/07/14 14:28:59+00,4200 - 4243 BLOCK OF BENNING ROAD NE,THEFT/OTHER,OTHERS,daytime,...,405049.0,136086.0,38.892605,-76.941800,921779026,NaN,True,True,non-violent,THEFT/OTHER
27930,399823.0,138853.0,20400676,2020/05/01 18:58:30+00,2020/05/01 15:00:00+00,2020/05/01 15:35:00+00,1948 - 2099 BLOCK OF 3RD STREET NE,THEFT F/AUTO,OTHERS,daytime,...,399823.0,138853.0,38.917546,-77.002041,921779089,NaN,True,True,non-violent,THEFT_F/AUTO
27931,400801.0,129945.0,20141517,2020/10/04 03:24:25+00,2020/10/04 01:03:42+00,2020/10/04 02:58:27+00,900 - 1299 BLOCK OF VALLEY AVENUE SE,MOTOR VEHICLE THEFT,OTHERS,nighttime,...,400801.0,129945.0,38.837298,-76.990774,921779151,NaN,True,False,non-violent,MOTOR_VEHICLE_THEFT

### Transforming column types

**Task**: check the type of the `START_DATE` column

In [82]:
df.START_DATE

0        2010/09/02 04:00:00+00
1        2020/01/11 02:48:51+00
2        2010/10/10 02:00:00+00
3        2019/12/30 20:00:20+00
4        2020/01/02 20:39:16+00
                  ...
27927    2020/07/06 20:42:59+00
27928    2020/07/07 18:00:45+00
27929    2020/07/11 22:00:31+00
27930    2020/05/01 15:00:00+00
27931    2020/10/04 01:03:42+00
Name: START_DATE, Length: 27932, dtype: object

**Task**: recast the `START_DATE` column to datetime, calling this `START_DATE_CLEAN`; coerce errors rather than cleaning the string; check the type of that new col

In [83]:
df["START_DATE_CLEAN"] = pd.to_datetime(df["START_DATE"], errors="coerce")

In [84]:
df.START_DATE_CLEAN

0       2010-09-02 04:00:00+00:00
1       2020-01-11 02:48:51+00:00
2       2010-10-10 02:00:00+00:00
3       2019-12-30 20:00:20+00:00
4       2020-01-02 20:39:16+00:00
                   ...
27927   2020-07-06 20:42:59+00:00
27928   2020-07-07 18:00:45+00:00
27929   2020-07-11 22:00:31+00:00
27930   2020-05-01 15:00:00+00:00
27931   2020-10-04 01:03:42+00:00
Name: START_DATE_CLEAN, Length: 27932, dtype: datetime64[ns, UTC]

**Task:** print the min and max of `START_DATE_CLEAN`. What happens if you try to do this with `START_DATE`?

In [85]:
df.START_DATE_CLEAN.min()

Timestamp('1940-02-17 00:00:16+0000', tz='UTC')

In [86]:
df.START_DATE_CLEAN.max()

Timestamp('2021-01-01 02:30:21+0000', tz='UTC')

In [87]:
df.START_DATE.min()

'1940/02/17 00:00:16+00'

In [88]:
df.START_DATE.max()

'2021/01/01 02:30:21+00'

## 3. Row and column filtering

### Row subsetting

**Task**: filter to crime reports about theft using the `is_theft` definition and that are in ward 3

In [94]:
df[ (df.is_theft == True) & (df.WARD == 3)][["OFFENSE", "WARD", "is_theft"]]

                   OFFENSE  WARD  is_theft
20            THEFT F/AUTO     3      True
24            THEFT F/AUTO     3      True
38             THEFT/OTHER     3      True
56            THEFT F/AUTO     3      True
62            THEFT F/AUTO     3      True
...                    ...   ...       ...
27883          THEFT/OTHER     3      True
27886  MOTOR VEHICLE THEFT     3      True
27887  MOTOR VEHICLE THEFT     3      True
27898         THEFT F/AUTO     3      True
27899          THEFT/OTHER     3      True

[1522 rows x 3 columns]

KeyError: 'is_theft_and_in_ward3'

### Column subsetting

**Task**: select two columns--`START_DATE` and `END_DATE`--and print the head of the dataframe

In [98]:
df[["START_DATE", "END_DATE"]].head()

               START_DATE                END_DATE
0  2010/09/02 04:00:00+00  2010/09/02 04:00:00+00
1  2020/01/11 02:48:51+00  2020/01/17 02:48:54+00
2  2010/10/10 02:00:00+00                     NaN
3  2019/12/30 20:00:20+00  2020/01/02 18:53:32+00
4  2020/01/02 20:39:16+00  2020/01/02 22:20:27+00

**Task**: use list comprehension to automate this a bit and select all columns with the word "DATE" in the name; print the head of the dataframe

In [99]:
columns_I_want = ["START_DATE", "END_DATE"]

In [100]:
df[columns_I_want].head()

               START_DATE                END_DATE
0  2010/09/02 04:00:00+00  2010/09/02 04:00:00+00
1  2020/01/11 02:48:51+00  2020/01/17 02:48:54+00
2  2010/10/10 02:00:00+00                     NaN
3  2019/12/30 20:00:20+00  2020/01/02 18:53:32+00
4  2020/01/02 20:39:16+00  2020/01/02 22:20:27+00

**Task**: filter reports of crime in `START_DATE_CLEAN` before May 2020 and that are located in ward 1; select the ward and `START_DATE` column and print a random sample of rows

In [102]:
df2 = df[ (df.START_DATE_CLEAN < "2020-05-01") & (df.WARD == 1) ]
df2[["WARD", "START_DATE"]].sample(frac=1)

       WARD              START_DATE
23207     1  2020/04/22 15:00:32+00
7440      1  2020/02/11 18:06:57+00
22328     1  2020/04/02 21:40:37+00
684       1  2020/02/17 23:00:27+00
16404     1  2020/03/16 18:20:04+00
...     ...                     ...
6837      1  2020/01/26 19:30:13+00
6749      1  2020/04/01 16:00:09+00
6526      1  2020/03/11 22:30:16+00
22196     1  2020/04/28 21:00:19+00
7902      1  2020/01/04 03:00:17+00

[1148 rows x 2 columns]